[package]
name = "bellperson"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK library"
documentation = "https://docs.rs/bellperson"
homepage = "https://github.com/filecoin-project/bellman"
license = "MIT/Apache-2.0"
repository = "https://github.com/filecoin-project/bellman"
version = "0.9.2"
readme = "README.md"
edition = "2018"

[dependencies]
bit-vec = "0.6"
blake2s_simd = "0.5"
ff = { version = "0.2.0", package = "fff" }
futures = "0.1"
futures-cpupool = { version = "0.1", optional = true }
groupy = "0.3.1"
num_cpus = { version = "1", optional = true }
crossbeam = { version = "0.7", optional = true }
paired = { version = "0.20.0", optional = true }
rand_core = "0.5"
byteorder = "1"
log = "0.4.8"
lazy_static = "1.4.0"
ocl = { version = "0.19.4", package = "fil-ocl", optional = true }
ff-cl-gen = { version = "0.1.1", optional = true }
fs2 = { version = "0.4.3", optional = true }
rand = "0.7"
rayon = "1.3.0"
memmap = "0.7.0"
thiserror = "1.0.10"
ahash = "0.3.4"
const-random = "= 0.1.8"
const-random-macro = "= 0.1.8"

[dev-dependencies]
hex-literal = "0.2"
rand_xorshift = "0.2"
sha2 = "0.8"
env_logger = "0.7.1"
criterion = "0.3.2"

[features]
default = ["groth16", "multicore"]
gpu = ["ocl", "ff-cl-gen", "fs2"]
groth16 = ["paired"]
multicore = ["futures-cpupool", "crossbeam", "num_cpus"]

[[test]]
name = "mimc"
path = "tests/mimc.rs"
required-features = ["groth16"]

[badges]
maintenance = { status = "actively-developed" }



[[bench]]
name = "lc"
harness = false
